export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const GET_USER_DATA_START = 'GET_USER_DATA_START';
export const GET_USER_DATA_SUCCESS = 'GET_USER_DATA_SUCCESS';
export const GET_USER_DATA_FAIL = 'GET_USER_DATA_FAIL';

export const SET_USER_DATA_START = 'SET_USER_DATA_START';
export const SET_NEW_USER_DATA_SUCCESS = 'GET_USER_DATA_SUCCESS';
export const SET_NEW_USER_DATA_FAIL = 'GET_USER_DATA_FAIL';

export const UPDATE_CURRENT_EXPENSE_START = 'UPDATE_CURRENT_EXPENSE_START';
export const UPDATE_CURRENT_EXPENSE_SUCCESS = 'UPDATE_CURRENT_EXPENSE_SUCCESS';
export const UPDATE_CURRENT_EXPENSE_FAIL = 'UPDATE_CURRENT_EXPENSE_FAIL';

export const UPDATE_START = 'UPDATE_START';
export const UPDATE_EXPENSE_SUCCESS = 'UPDATE_EXPENSE_SUCCESS';
export const UPDATE_FAIL = 'UPDATE_FAIL';