/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransfersRouteImport } from './routes/transfers'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RecurringRouteImport } from './routes/recurring'
import { Route as NetWorthRouteImport } from './routes/net-worth'
import { Route as InvestmentsRouteImport } from './routes/investments'
import { Route as ImportRouteImport } from './routes/import'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as BudgetsRouteImport } from './routes/budgets'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TransactionsNewRouteImport } from './routes/transactions_.new'
import { Route as ApiTransfersRouteImport } from './routes/api/transfers'
import { Route as ApiTransactionsRouteImport } from './routes/api/transactions'
import { Route as ApiRecurringRouteImport } from './routes/api/recurring'
import { Route as ApiNetWorthRouteImport } from './routes/api/net-worth'
import { Route as ApiInvestmentsRouteImport } from './routes/api/investments'
import { Route as ApiImportRouteImport } from './routes/api/import'
import { Route as ApiHoldingsRouteImport } from './routes/api/holdings'
import { Route as ApiExportRouteImport } from './routes/api/export'
import { Route as ApiCategoriesRouteImport } from './routes/api/categories'
import { Route as ApiBudgetsRouteImport } from './routes/api/budgets'
import { Route as ApiAccountsRouteImport } from './routes/api/accounts'
import { Route as TransactionsIdEditRouteImport } from './routes/transactions_.$id.edit'
import { Route as ApiTransfersIdRouteImport } from './routes/api/transfers.$id'
import { Route as ApiTransactionsIdRouteImport } from './routes/api/transactions.$id'
import { Route as ApiStatsMonthlySummaryRouteImport } from './routes/api/stats.monthly-summary'
import { Route as ApiStatsCategoryBreakdownRouteImport } from './routes/api/stats.category-breakdown'
import { Route as ApiRecurringIdRouteImport } from './routes/api/recurring.$id'
import { Route as ApiNetWorthSnapshotsRouteImport } from './routes/api/net-worth.snapshots'
import { Route as ApiInvestmentsIdRouteImport } from './routes/api/investments.$id'
import { Route as ApiHoldingsIdRouteImport } from './routes/api/holdings.$id'
import { Route as ApiCategoriesIdRouteImport } from './routes/api/categories.$id'
import { Route as ApiBudgetsCategoryIdRouteImport } from './routes/api/budgets.$categoryId'
import { Route as ApiAccountsIdRouteImport } from './routes/api/accounts.$id'
import { Route as ApiNetWorthSnapshotsIdRouteImport } from './routes/api/net-worth.snapshots.$id'
import { Route as ApiAccountsIdReconcileRouteImport } from './routes/api/accounts.$id.reconcile'

const TransfersRoute = TransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RecurringRoute = RecurringRouteImport.update({
  id: '/recurring',
  path: '/recurring',
  getParentRoute: () => rootRouteImport,
} as any)
const NetWorthRoute = NetWorthRouteImport.update({
  id: '/net-worth',
  path: '/net-worth',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentsRoute = InvestmentsRouteImport.update({
  id: '/investments',
  path: '/investments',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetsRoute = BudgetsRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsNewRoute = TransactionsNewRouteImport.update({
  id: '/transactions_/new',
  path: '/transactions/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTransfersRoute = ApiTransfersRouteImport.update({
  id: '/api/transfers',
  path: '/api/transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTransactionsRoute = ApiTransactionsRouteImport.update({
  id: '/api/transactions',
  path: '/api/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecurringRoute = ApiRecurringRouteImport.update({
  id: '/api/recurring',
  path: '/api/recurring',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNetWorthRoute = ApiNetWorthRouteImport.update({
  id: '/api/net-worth',
  path: '/api/net-worth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInvestmentsRoute = ApiInvestmentsRouteImport.update({
  id: '/api/investments',
  path: '/api/investments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImportRoute = ApiImportRouteImport.update({
  id: '/api/import',
  path: '/api/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHoldingsRoute = ApiHoldingsRouteImport.update({
  id: '/api/holdings',
  path: '/api/holdings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExportRoute = ApiExportRouteImport.update({
  id: '/api/export',
  path: '/api/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCategoriesRoute = ApiCategoriesRouteImport.update({
  id: '/api/categories',
  path: '/api/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBudgetsRoute = ApiBudgetsRouteImport.update({
  id: '/api/budgets',
  path: '/api/budgets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountsRoute = ApiAccountsRouteImport.update({
  id: '/api/accounts',
  path: '/api/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsIdEditRoute = TransactionsIdEditRouteImport.update({
  id: '/transactions_/$id/edit',
  path: '/transactions/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTransfersIdRoute = ApiTransfersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiTransfersRoute,
} as any)
const ApiTransactionsIdRoute = ApiTransactionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiTransactionsRoute,
} as any)
const ApiStatsMonthlySummaryRoute = ApiStatsMonthlySummaryRouteImport.update({
  id: '/api/stats/monthly-summary',
  path: '/api/stats/monthly-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatsCategoryBreakdownRoute =
  ApiStatsCategoryBreakdownRouteImport.update({
    id: '/api/stats/category-breakdown',
    path: '/api/stats/category-breakdown',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiRecurringIdRoute = ApiRecurringIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiRecurringRoute,
} as any)
const ApiNetWorthSnapshotsRoute = ApiNetWorthSnapshotsRouteImport.update({
  id: '/snapshots',
  path: '/snapshots',
  getParentRoute: () => ApiNetWorthRoute,
} as any)
const ApiInvestmentsIdRoute = ApiInvestmentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiInvestmentsRoute,
} as any)
const ApiHoldingsIdRoute = ApiHoldingsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiHoldingsRoute,
} as any)
const ApiCategoriesIdRoute = ApiCategoriesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiCategoriesRoute,
} as any)
const ApiBudgetsCategoryIdRoute = ApiBudgetsCategoryIdRouteImport.update({
  id: '/$categoryId',
  path: '/$categoryId',
  getParentRoute: () => ApiBudgetsRoute,
} as any)
const ApiAccountsIdRoute = ApiAccountsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAccountsRoute,
} as any)
const ApiNetWorthSnapshotsIdRoute = ApiNetWorthSnapshotsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiNetWorthSnapshotsRoute,
} as any)
const ApiAccountsIdReconcileRoute = ApiAccountsIdReconcileRouteImport.update({
  id: '/reconcile',
  path: '/reconcile',
  getParentRoute: () => ApiAccountsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/budgets': typeof BudgetsRoute
  '/categories': typeof CategoriesRoute
  '/import': typeof ImportRoute
  '/investments': typeof InvestmentsRoute
  '/net-worth': typeof NetWorthRoute
  '/recurring': typeof RecurringRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/transactions': typeof TransactionsRoute
  '/transfers': typeof TransfersRoute
  '/api/accounts': typeof ApiAccountsRouteWithChildren
  '/api/budgets': typeof ApiBudgetsRouteWithChildren
  '/api/categories': typeof ApiCategoriesRouteWithChildren
  '/api/export': typeof ApiExportRoute
  '/api/holdings': typeof ApiHoldingsRouteWithChildren
  '/api/import': typeof ApiImportRoute
  '/api/investments': typeof ApiInvestmentsRouteWithChildren
  '/api/net-worth': typeof ApiNetWorthRouteWithChildren
  '/api/recurring': typeof ApiRecurringRouteWithChildren
  '/api/transactions': typeof ApiTransactionsRouteWithChildren
  '/api/transfers': typeof ApiTransfersRouteWithChildren
  '/transactions/new': typeof TransactionsNewRoute
  '/api/accounts/$id': typeof ApiAccountsIdRouteWithChildren
  '/api/budgets/$categoryId': typeof ApiBudgetsCategoryIdRoute
  '/api/categories/$id': typeof ApiCategoriesIdRoute
  '/api/holdings/$id': typeof ApiHoldingsIdRoute
  '/api/investments/$id': typeof ApiInvestmentsIdRoute
  '/api/net-worth/snapshots': typeof ApiNetWorthSnapshotsRouteWithChildren
  '/api/recurring/$id': typeof ApiRecurringIdRoute
  '/api/stats/category-breakdown': typeof ApiStatsCategoryBreakdownRoute
  '/api/stats/monthly-summary': typeof ApiStatsMonthlySummaryRoute
  '/api/transactions/$id': typeof ApiTransactionsIdRoute
  '/api/transfers/$id': typeof ApiTransfersIdRoute
  '/transactions/$id/edit': typeof TransactionsIdEditRoute
  '/api/accounts/$id/reconcile': typeof ApiAccountsIdReconcileRoute
  '/api/net-worth/snapshots/$id': typeof ApiNetWorthSnapshotsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/budgets': typeof BudgetsRoute
  '/categories': typeof CategoriesRoute
  '/import': typeof ImportRoute
  '/investments': typeof InvestmentsRoute
  '/net-worth': typeof NetWorthRoute
  '/recurring': typeof RecurringRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/transactions': typeof TransactionsRoute
  '/transfers': typeof TransfersRoute
  '/api/accounts': typeof ApiAccountsRouteWithChildren
  '/api/budgets': typeof ApiBudgetsRouteWithChildren
  '/api/categories': typeof ApiCategoriesRouteWithChildren
  '/api/export': typeof ApiExportRoute
  '/api/holdings': typeof ApiHoldingsRouteWithChildren
  '/api/import': typeof ApiImportRoute
  '/api/investments': typeof ApiInvestmentsRouteWithChildren
  '/api/net-worth': typeof ApiNetWorthRouteWithChildren
  '/api/recurring': typeof ApiRecurringRouteWithChildren
  '/api/transactions': typeof ApiTransactionsRouteWithChildren
  '/api/transfers': typeof ApiTransfersRouteWithChildren
  '/transactions/new': typeof TransactionsNewRoute
  '/api/accounts/$id': typeof ApiAccountsIdRouteWithChildren
  '/api/budgets/$categoryId': typeof ApiBudgetsCategoryIdRoute
  '/api/categories/$id': typeof ApiCategoriesIdRoute
  '/api/holdings/$id': typeof ApiHoldingsIdRoute
  '/api/investments/$id': typeof ApiInvestmentsIdRoute
  '/api/net-worth/snapshots': typeof ApiNetWorthSnapshotsRouteWithChildren
  '/api/recurring/$id': typeof ApiRecurringIdRoute
  '/api/stats/category-breakdown': typeof ApiStatsCategoryBreakdownRoute
  '/api/stats/monthly-summary': typeof ApiStatsMonthlySummaryRoute
  '/api/transactions/$id': typeof ApiTransactionsIdRoute
  '/api/transfers/$id': typeof ApiTransfersIdRoute
  '/transactions/$id/edit': typeof TransactionsIdEditRoute
  '/api/accounts/$id/reconcile': typeof ApiAccountsIdReconcileRoute
  '/api/net-worth/snapshots/$id': typeof ApiNetWorthSnapshotsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/budgets': typeof BudgetsRoute
  '/categories': typeof CategoriesRoute
  '/import': typeof ImportRoute
  '/investments': typeof InvestmentsRoute
  '/net-worth': typeof NetWorthRoute
  '/recurring': typeof RecurringRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/transactions': typeof TransactionsRoute
  '/transfers': typeof TransfersRoute
  '/api/accounts': typeof ApiAccountsRouteWithChildren
  '/api/budgets': typeof ApiBudgetsRouteWithChildren
  '/api/categories': typeof ApiCategoriesRouteWithChildren
  '/api/export': typeof ApiExportRoute
  '/api/holdings': typeof ApiHoldingsRouteWithChildren
  '/api/import': typeof ApiImportRoute
  '/api/investments': typeof ApiInvestmentsRouteWithChildren
  '/api/net-worth': typeof ApiNetWorthRouteWithChildren
  '/api/recurring': typeof ApiRecurringRouteWithChildren
  '/api/transactions': typeof ApiTransactionsRouteWithChildren
  '/api/transfers': typeof ApiTransfersRouteWithChildren
  '/transactions_/new': typeof TransactionsNewRoute
  '/api/accounts/$id': typeof ApiAccountsIdRouteWithChildren
  '/api/budgets/$categoryId': typeof ApiBudgetsCategoryIdRoute
  '/api/categories/$id': typeof ApiCategoriesIdRoute
  '/api/holdings/$id': typeof ApiHoldingsIdRoute
  '/api/investments/$id': typeof ApiInvestmentsIdRoute
  '/api/net-worth/snapshots': typeof ApiNetWorthSnapshotsRouteWithChildren
  '/api/recurring/$id': typeof ApiRecurringIdRoute
  '/api/stats/category-breakdown': typeof ApiStatsCategoryBreakdownRoute
  '/api/stats/monthly-summary': typeof ApiStatsMonthlySummaryRoute
  '/api/transactions/$id': typeof ApiTransactionsIdRoute
  '/api/transfers/$id': typeof ApiTransfersIdRoute
  '/transactions_/$id/edit': typeof TransactionsIdEditRoute
  '/api/accounts/$id/reconcile': typeof ApiAccountsIdReconcileRoute
  '/api/net-worth/snapshots/$id': typeof ApiNetWorthSnapshotsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/budgets'
    | '/categories'
    | '/import'
    | '/investments'
    | '/net-worth'
    | '/recurring'
    | '/settings'
    | '/stats'
    | '/transactions'
    | '/transfers'
    | '/api/accounts'
    | '/api/budgets'
    | '/api/categories'
    | '/api/export'
    | '/api/holdings'
    | '/api/import'
    | '/api/investments'
    | '/api/net-worth'
    | '/api/recurring'
    | '/api/transactions'
    | '/api/transfers'
    | '/transactions/new'
    | '/api/accounts/$id'
    | '/api/budgets/$categoryId'
    | '/api/categories/$id'
    | '/api/holdings/$id'
    | '/api/investments/$id'
    | '/api/net-worth/snapshots'
    | '/api/recurring/$id'
    | '/api/stats/category-breakdown'
    | '/api/stats/monthly-summary'
    | '/api/transactions/$id'
    | '/api/transfers/$id'
    | '/transactions/$id/edit'
    | '/api/accounts/$id/reconcile'
    | '/api/net-worth/snapshots/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/budgets'
    | '/categories'
    | '/import'
    | '/investments'
    | '/net-worth'
    | '/recurring'
    | '/settings'
    | '/stats'
    | '/transactions'
    | '/transfers'
    | '/api/accounts'
    | '/api/budgets'
    | '/api/categories'
    | '/api/export'
    | '/api/holdings'
    | '/api/import'
    | '/api/investments'
    | '/api/net-worth'
    | '/api/recurring'
    | '/api/transactions'
    | '/api/transfers'
    | '/transactions/new'
    | '/api/accounts/$id'
    | '/api/budgets/$categoryId'
    | '/api/categories/$id'
    | '/api/holdings/$id'
    | '/api/investments/$id'
    | '/api/net-worth/snapshots'
    | '/api/recurring/$id'
    | '/api/stats/category-breakdown'
    | '/api/stats/monthly-summary'
    | '/api/transactions/$id'
    | '/api/transfers/$id'
    | '/transactions/$id/edit'
    | '/api/accounts/$id/reconcile'
    | '/api/net-worth/snapshots/$id'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/budgets'
    | '/categories'
    | '/import'
    | '/investments'
    | '/net-worth'
    | '/recurring'
    | '/settings'
    | '/stats'
    | '/transactions'
    | '/transfers'
    | '/api/accounts'
    | '/api/budgets'
    | '/api/categories'
    | '/api/export'
    | '/api/holdings'
    | '/api/import'
    | '/api/investments'
    | '/api/net-worth'
    | '/api/recurring'
    | '/api/transactions'
    | '/api/transfers'
    | '/transactions_/new'
    | '/api/accounts/$id'
    | '/api/budgets/$categoryId'
    | '/api/categories/$id'
    | '/api/holdings/$id'
    | '/api/investments/$id'
    | '/api/net-worth/snapshots'
    | '/api/recurring/$id'
    | '/api/stats/category-breakdown'
    | '/api/stats/monthly-summary'
    | '/api/transactions/$id'
    | '/api/transfers/$id'
    | '/transactions_/$id/edit'
    | '/api/accounts/$id/reconcile'
    | '/api/net-worth/snapshots/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRoute
  BudgetsRoute: typeof BudgetsRoute
  CategoriesRoute: typeof CategoriesRoute
  ImportRoute: typeof ImportRoute
  InvestmentsRoute: typeof InvestmentsRoute
  NetWorthRoute: typeof NetWorthRoute
  RecurringRoute: typeof RecurringRoute
  SettingsRoute: typeof SettingsRoute
  StatsRoute: typeof StatsRoute
  TransactionsRoute: typeof TransactionsRoute
  TransfersRoute: typeof TransfersRoute
  ApiAccountsRoute: typeof ApiAccountsRouteWithChildren
  ApiBudgetsRoute: typeof ApiBudgetsRouteWithChildren
  ApiCategoriesRoute: typeof ApiCategoriesRouteWithChildren
  ApiExportRoute: typeof ApiExportRoute
  ApiHoldingsRoute: typeof ApiHoldingsRouteWithChildren
  ApiImportRoute: typeof ApiImportRoute
  ApiInvestmentsRoute: typeof ApiInvestmentsRouteWithChildren
  ApiNetWorthRoute: typeof ApiNetWorthRouteWithChildren
  ApiRecurringRoute: typeof ApiRecurringRouteWithChildren
  ApiTransactionsRoute: typeof ApiTransactionsRouteWithChildren
  ApiTransfersRoute: typeof ApiTransfersRouteWithChildren
  TransactionsNewRoute: typeof TransactionsNewRoute
  ApiStatsCategoryBreakdownRoute: typeof ApiStatsCategoryBreakdownRoute
  ApiStatsMonthlySummaryRoute: typeof ApiStatsMonthlySummaryRoute
  TransactionsIdEditRoute: typeof TransactionsIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transfers': {
      id: '/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof TransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recurring': {
      id: '/recurring'
      path: '/recurring'
      fullPath: '/recurring'
      preLoaderRoute: typeof RecurringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/net-worth': {
      id: '/net-worth'
      path: '/net-worth'
      fullPath: '/net-worth'
      preLoaderRoute: typeof NetWorthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investments': {
      id: '/investments'
      path: '/investments'
      fullPath: '/investments'
      preLoaderRoute: typeof InvestmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budgets': {
      id: '/budgets'
      path: '/budgets'
      fullPath: '/budgets'
      preLoaderRoute: typeof BudgetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions_/new': {
      id: '/transactions_/new'
      path: '/transactions/new'
      fullPath: '/transactions/new'
      preLoaderRoute: typeof TransactionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transfers': {
      id: '/api/transfers'
      path: '/api/transfers'
      fullPath: '/api/transfers'
      preLoaderRoute: typeof ApiTransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transactions': {
      id: '/api/transactions'
      path: '/api/transactions'
      fullPath: '/api/transactions'
      preLoaderRoute: typeof ApiTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/recurring': {
      id: '/api/recurring'
      path: '/api/recurring'
      fullPath: '/api/recurring'
      preLoaderRoute: typeof ApiRecurringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/net-worth': {
      id: '/api/net-worth'
      path: '/api/net-worth'
      fullPath: '/api/net-worth'
      preLoaderRoute: typeof ApiNetWorthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/investments': {
      id: '/api/investments'
      path: '/api/investments'
      fullPath: '/api/investments'
      preLoaderRoute: typeof ApiInvestmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/import': {
      id: '/api/import'
      path: '/api/import'
      fullPath: '/api/import'
      preLoaderRoute: typeof ApiImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/holdings': {
      id: '/api/holdings'
      path: '/api/holdings'
      fullPath: '/api/holdings'
      preLoaderRoute: typeof ApiHoldingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/export': {
      id: '/api/export'
      path: '/api/export'
      fullPath: '/api/export'
      preLoaderRoute: typeof ApiExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/categories': {
      id: '/api/categories'
      path: '/api/categories'
      fullPath: '/api/categories'
      preLoaderRoute: typeof ApiCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/budgets': {
      id: '/api/budgets'
      path: '/api/budgets'
      fullPath: '/api/budgets'
      preLoaderRoute: typeof ApiBudgetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/accounts': {
      id: '/api/accounts'
      path: '/api/accounts'
      fullPath: '/api/accounts'
      preLoaderRoute: typeof ApiAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions_/$id/edit': {
      id: '/transactions_/$id/edit'
      path: '/transactions/$id/edit'
      fullPath: '/transactions/$id/edit'
      preLoaderRoute: typeof TransactionsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transfers/$id': {
      id: '/api/transfers/$id'
      path: '/$id'
      fullPath: '/api/transfers/$id'
      preLoaderRoute: typeof ApiTransfersIdRouteImport
      parentRoute: typeof ApiTransfersRoute
    }
    '/api/transactions/$id': {
      id: '/api/transactions/$id'
      path: '/$id'
      fullPath: '/api/transactions/$id'
      preLoaderRoute: typeof ApiTransactionsIdRouteImport
      parentRoute: typeof ApiTransactionsRoute
    }
    '/api/stats/monthly-summary': {
      id: '/api/stats/monthly-summary'
      path: '/api/stats/monthly-summary'
      fullPath: '/api/stats/monthly-summary'
      preLoaderRoute: typeof ApiStatsMonthlySummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stats/category-breakdown': {
      id: '/api/stats/category-breakdown'
      path: '/api/stats/category-breakdown'
      fullPath: '/api/stats/category-breakdown'
      preLoaderRoute: typeof ApiStatsCategoryBreakdownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/recurring/$id': {
      id: '/api/recurring/$id'
      path: '/$id'
      fullPath: '/api/recurring/$id'
      preLoaderRoute: typeof ApiRecurringIdRouteImport
      parentRoute: typeof ApiRecurringRoute
    }
    '/api/net-worth/snapshots': {
      id: '/api/net-worth/snapshots'
      path: '/snapshots'
      fullPath: '/api/net-worth/snapshots'
      preLoaderRoute: typeof ApiNetWorthSnapshotsRouteImport
      parentRoute: typeof ApiNetWorthRoute
    }
    '/api/investments/$id': {
      id: '/api/investments/$id'
      path: '/$id'
      fullPath: '/api/investments/$id'
      preLoaderRoute: typeof ApiInvestmentsIdRouteImport
      parentRoute: typeof ApiInvestmentsRoute
    }
    '/api/holdings/$id': {
      id: '/api/holdings/$id'
      path: '/$id'
      fullPath: '/api/holdings/$id'
      preLoaderRoute: typeof ApiHoldingsIdRouteImport
      parentRoute: typeof ApiHoldingsRoute
    }
    '/api/categories/$id': {
      id: '/api/categories/$id'
      path: '/$id'
      fullPath: '/api/categories/$id'
      preLoaderRoute: typeof ApiCategoriesIdRouteImport
      parentRoute: typeof ApiCategoriesRoute
    }
    '/api/budgets/$categoryId': {
      id: '/api/budgets/$categoryId'
      path: '/$categoryId'
      fullPath: '/api/budgets/$categoryId'
      preLoaderRoute: typeof ApiBudgetsCategoryIdRouteImport
      parentRoute: typeof ApiBudgetsRoute
    }
    '/api/accounts/$id': {
      id: '/api/accounts/$id'
      path: '/$id'
      fullPath: '/api/accounts/$id'
      preLoaderRoute: typeof ApiAccountsIdRouteImport
      parentRoute: typeof ApiAccountsRoute
    }
    '/api/net-worth/snapshots/$id': {
      id: '/api/net-worth/snapshots/$id'
      path: '/$id'
      fullPath: '/api/net-worth/snapshots/$id'
      preLoaderRoute: typeof ApiNetWorthSnapshotsIdRouteImport
      parentRoute: typeof ApiNetWorthSnapshotsRoute
    }
    '/api/accounts/$id/reconcile': {
      id: '/api/accounts/$id/reconcile'
      path: '/reconcile'
      fullPath: '/api/accounts/$id/reconcile'
      preLoaderRoute: typeof ApiAccountsIdReconcileRouteImport
      parentRoute: typeof ApiAccountsIdRoute
    }
  }
}

interface ApiAccountsIdRouteChildren {
  ApiAccountsIdReconcileRoute: typeof ApiAccountsIdReconcileRoute
}

const ApiAccountsIdRouteChildren: ApiAccountsIdRouteChildren = {
  ApiAccountsIdReconcileRoute: ApiAccountsIdReconcileRoute,
}

const ApiAccountsIdRouteWithChildren = ApiAccountsIdRoute._addFileChildren(
  ApiAccountsIdRouteChildren,
)

interface ApiAccountsRouteChildren {
  ApiAccountsIdRoute: typeof ApiAccountsIdRouteWithChildren
}

const ApiAccountsRouteChildren: ApiAccountsRouteChildren = {
  ApiAccountsIdRoute: ApiAccountsIdRouteWithChildren,
}

const ApiAccountsRouteWithChildren = ApiAccountsRoute._addFileChildren(
  ApiAccountsRouteChildren,
)

interface ApiBudgetsRouteChildren {
  ApiBudgetsCategoryIdRoute: typeof ApiBudgetsCategoryIdRoute
}

const ApiBudgetsRouteChildren: ApiBudgetsRouteChildren = {
  ApiBudgetsCategoryIdRoute: ApiBudgetsCategoryIdRoute,
}

const ApiBudgetsRouteWithChildren = ApiBudgetsRoute._addFileChildren(
  ApiBudgetsRouteChildren,
)

interface ApiCategoriesRouteChildren {
  ApiCategoriesIdRoute: typeof ApiCategoriesIdRoute
}

const ApiCategoriesRouteChildren: ApiCategoriesRouteChildren = {
  ApiCategoriesIdRoute: ApiCategoriesIdRoute,
}

const ApiCategoriesRouteWithChildren = ApiCategoriesRoute._addFileChildren(
  ApiCategoriesRouteChildren,
)

interface ApiHoldingsRouteChildren {
  ApiHoldingsIdRoute: typeof ApiHoldingsIdRoute
}

const ApiHoldingsRouteChildren: ApiHoldingsRouteChildren = {
  ApiHoldingsIdRoute: ApiHoldingsIdRoute,
}

const ApiHoldingsRouteWithChildren = ApiHoldingsRoute._addFileChildren(
  ApiHoldingsRouteChildren,
)

interface ApiInvestmentsRouteChildren {
  ApiInvestmentsIdRoute: typeof ApiInvestmentsIdRoute
}

const ApiInvestmentsRouteChildren: ApiInvestmentsRouteChildren = {
  ApiInvestmentsIdRoute: ApiInvestmentsIdRoute,
}

const ApiInvestmentsRouteWithChildren = ApiInvestmentsRoute._addFileChildren(
  ApiInvestmentsRouteChildren,
)

interface ApiNetWorthSnapshotsRouteChildren {
  ApiNetWorthSnapshotsIdRoute: typeof ApiNetWorthSnapshotsIdRoute
}

const ApiNetWorthSnapshotsRouteChildren: ApiNetWorthSnapshotsRouteChildren = {
  ApiNetWorthSnapshotsIdRoute: ApiNetWorthSnapshotsIdRoute,
}

const ApiNetWorthSnapshotsRouteWithChildren =
  ApiNetWorthSnapshotsRoute._addFileChildren(ApiNetWorthSnapshotsRouteChildren)

interface ApiNetWorthRouteChildren {
  ApiNetWorthSnapshotsRoute: typeof ApiNetWorthSnapshotsRouteWithChildren
}

const ApiNetWorthRouteChildren: ApiNetWorthRouteChildren = {
  ApiNetWorthSnapshotsRoute: ApiNetWorthSnapshotsRouteWithChildren,
}

const ApiNetWorthRouteWithChildren = ApiNetWorthRoute._addFileChildren(
  ApiNetWorthRouteChildren,
)

interface ApiRecurringRouteChildren {
  ApiRecurringIdRoute: typeof ApiRecurringIdRoute
}

const ApiRecurringRouteChildren: ApiRecurringRouteChildren = {
  ApiRecurringIdRoute: ApiRecurringIdRoute,
}

const ApiRecurringRouteWithChildren = ApiRecurringRoute._addFileChildren(
  ApiRecurringRouteChildren,
)

interface ApiTransactionsRouteChildren {
  ApiTransactionsIdRoute: typeof ApiTransactionsIdRoute
}

const ApiTransactionsRouteChildren: ApiTransactionsRouteChildren = {
  ApiTransactionsIdRoute: ApiTransactionsIdRoute,
}

const ApiTransactionsRouteWithChildren = ApiTransactionsRoute._addFileChildren(
  ApiTransactionsRouteChildren,
)

interface ApiTransfersRouteChildren {
  ApiTransfersIdRoute: typeof ApiTransfersIdRoute
}

const ApiTransfersRouteChildren: ApiTransfersRouteChildren = {
  ApiTransfersIdRoute: ApiTransfersIdRoute,
}

const ApiTransfersRouteWithChildren = ApiTransfersRoute._addFileChildren(
  ApiTransfersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRoute,
  BudgetsRoute: BudgetsRoute,
  CategoriesRoute: CategoriesRoute,
  ImportRoute: ImportRoute,
  InvestmentsRoute: InvestmentsRoute,
  NetWorthRoute: NetWorthRoute,
  RecurringRoute: RecurringRoute,
  SettingsRoute: SettingsRoute,
  StatsRoute: StatsRoute,
  TransactionsRoute: TransactionsRoute,
  TransfersRoute: TransfersRoute,
  ApiAccountsRoute: ApiAccountsRouteWithChildren,
  ApiBudgetsRoute: ApiBudgetsRouteWithChildren,
  ApiCategoriesRoute: ApiCategoriesRouteWithChildren,
  ApiExportRoute: ApiExportRoute,
  ApiHoldingsRoute: ApiHoldingsRouteWithChildren,
  ApiImportRoute: ApiImportRoute,
  ApiInvestmentsRoute: ApiInvestmentsRouteWithChildren,
  ApiNetWorthRoute: ApiNetWorthRouteWithChildren,
  ApiRecurringRoute: ApiRecurringRouteWithChildren,
  ApiTransactionsRoute: ApiTransactionsRouteWithChildren,
  ApiTransfersRoute: ApiTransfersRouteWithChildren,
  TransactionsNewRoute: TransactionsNewRoute,
  ApiStatsCategoryBreakdownRoute: ApiStatsCategoryBreakdownRoute,
  ApiStatsMonthlySummaryRoute: ApiStatsMonthlySummaryRoute,
  TransactionsIdEditRoute: TransactionsIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
