/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as RecurringRouteImport } from './routes/recurring'
import { Route as InvestmentsRouteImport } from './routes/investments'
import { Route as ImportRouteImport } from './routes/import'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TransactionsNewRouteImport } from './routes/transactions_.new'
import { Route as ApiTransactionsRouteImport } from './routes/api/transactions'
import { Route as ApiRecurringRouteImport } from './routes/api/recurring'
import { Route as ApiInvestmentsRouteImport } from './routes/api/investments'
import { Route as ApiImportRouteImport } from './routes/api/import'
import { Route as ApiExportRouteImport } from './routes/api/export'
import { Route as ApiCategoriesRouteImport } from './routes/api/categories'
import { Route as TransactionsIdEditRouteImport } from './routes/transactions_.$id.edit'
import { Route as ApiTransactionsIdRouteImport } from './routes/api/transactions.$id'
import { Route as ApiStatsMonthlySummaryRouteImport } from './routes/api/stats.monthly-summary'
import { Route as ApiStatsCategoryBreakdownRouteImport } from './routes/api/stats.category-breakdown'
import { Route as ApiRecurringIdRouteImport } from './routes/api/recurring.$id'
import { Route as ApiInvestmentsIdRouteImport } from './routes/api/investments.$id'
import { Route as ApiCategoriesIdRouteImport } from './routes/api/categories.$id'

const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const RecurringRoute = RecurringRouteImport.update({
  id: '/recurring',
  path: '/recurring',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentsRoute = InvestmentsRouteImport.update({
  id: '/investments',
  path: '/investments',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsNewRoute = TransactionsNewRouteImport.update({
  id: '/transactions_/new',
  path: '/transactions/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTransactionsRoute = ApiTransactionsRouteImport.update({
  id: '/api/transactions',
  path: '/api/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecurringRoute = ApiRecurringRouteImport.update({
  id: '/api/recurring',
  path: '/api/recurring',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInvestmentsRoute = ApiInvestmentsRouteImport.update({
  id: '/api/investments',
  path: '/api/investments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImportRoute = ApiImportRouteImport.update({
  id: '/api/import',
  path: '/api/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExportRoute = ApiExportRouteImport.update({
  id: '/api/export',
  path: '/api/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCategoriesRoute = ApiCategoriesRouteImport.update({
  id: '/api/categories',
  path: '/api/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsIdEditRoute = TransactionsIdEditRouteImport.update({
  id: '/transactions_/$id/edit',
  path: '/transactions/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTransactionsIdRoute = ApiTransactionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiTransactionsRoute,
} as any)
const ApiStatsMonthlySummaryRoute = ApiStatsMonthlySummaryRouteImport.update({
  id: '/api/stats/monthly-summary',
  path: '/api/stats/monthly-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatsCategoryBreakdownRoute =
  ApiStatsCategoryBreakdownRouteImport.update({
    id: '/api/stats/category-breakdown',
    path: '/api/stats/category-breakdown',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiRecurringIdRoute = ApiRecurringIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiRecurringRoute,
} as any)
const ApiInvestmentsIdRoute = ApiInvestmentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiInvestmentsRoute,
} as any)
const ApiCategoriesIdRoute = ApiCategoriesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiCategoriesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/import': typeof ImportRoute
  '/investments': typeof InvestmentsRoute
  '/recurring': typeof RecurringRoute
  '/stats': typeof StatsRoute
  '/transactions': typeof TransactionsRoute
  '/api/categories': typeof ApiCategoriesRouteWithChildren
  '/api/export': typeof ApiExportRoute
  '/api/import': typeof ApiImportRoute
  '/api/investments': typeof ApiInvestmentsRouteWithChildren
  '/api/recurring': typeof ApiRecurringRouteWithChildren
  '/api/transactions': typeof ApiTransactionsRouteWithChildren
  '/transactions/new': typeof TransactionsNewRoute
  '/api/categories/$id': typeof ApiCategoriesIdRoute
  '/api/investments/$id': typeof ApiInvestmentsIdRoute
  '/api/recurring/$id': typeof ApiRecurringIdRoute
  '/api/stats/category-breakdown': typeof ApiStatsCategoryBreakdownRoute
  '/api/stats/monthly-summary': typeof ApiStatsMonthlySummaryRoute
  '/api/transactions/$id': typeof ApiTransactionsIdRoute
  '/transactions/$id/edit': typeof TransactionsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/import': typeof ImportRoute
  '/investments': typeof InvestmentsRoute
  '/recurring': typeof RecurringRoute
  '/stats': typeof StatsRoute
  '/transactions': typeof TransactionsRoute
  '/api/categories': typeof ApiCategoriesRouteWithChildren
  '/api/export': typeof ApiExportRoute
  '/api/import': typeof ApiImportRoute
  '/api/investments': typeof ApiInvestmentsRouteWithChildren
  '/api/recurring': typeof ApiRecurringRouteWithChildren
  '/api/transactions': typeof ApiTransactionsRouteWithChildren
  '/transactions/new': typeof TransactionsNewRoute
  '/api/categories/$id': typeof ApiCategoriesIdRoute
  '/api/investments/$id': typeof ApiInvestmentsIdRoute
  '/api/recurring/$id': typeof ApiRecurringIdRoute
  '/api/stats/category-breakdown': typeof ApiStatsCategoryBreakdownRoute
  '/api/stats/monthly-summary': typeof ApiStatsMonthlySummaryRoute
  '/api/transactions/$id': typeof ApiTransactionsIdRoute
  '/transactions/$id/edit': typeof TransactionsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/import': typeof ImportRoute
  '/investments': typeof InvestmentsRoute
  '/recurring': typeof RecurringRoute
  '/stats': typeof StatsRoute
  '/transactions': typeof TransactionsRoute
  '/api/categories': typeof ApiCategoriesRouteWithChildren
  '/api/export': typeof ApiExportRoute
  '/api/import': typeof ApiImportRoute
  '/api/investments': typeof ApiInvestmentsRouteWithChildren
  '/api/recurring': typeof ApiRecurringRouteWithChildren
  '/api/transactions': typeof ApiTransactionsRouteWithChildren
  '/transactions_/new': typeof TransactionsNewRoute
  '/api/categories/$id': typeof ApiCategoriesIdRoute
  '/api/investments/$id': typeof ApiInvestmentsIdRoute
  '/api/recurring/$id': typeof ApiRecurringIdRoute
  '/api/stats/category-breakdown': typeof ApiStatsCategoryBreakdownRoute
  '/api/stats/monthly-summary': typeof ApiStatsMonthlySummaryRoute
  '/api/transactions/$id': typeof ApiTransactionsIdRoute
  '/transactions_/$id/edit': typeof TransactionsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/categories'
    | '/import'
    | '/investments'
    | '/recurring'
    | '/stats'
    | '/transactions'
    | '/api/categories'
    | '/api/export'
    | '/api/import'
    | '/api/investments'
    | '/api/recurring'
    | '/api/transactions'
    | '/transactions/new'
    | '/api/categories/$id'
    | '/api/investments/$id'
    | '/api/recurring/$id'
    | '/api/stats/category-breakdown'
    | '/api/stats/monthly-summary'
    | '/api/transactions/$id'
    | '/transactions/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/categories'
    | '/import'
    | '/investments'
    | '/recurring'
    | '/stats'
    | '/transactions'
    | '/api/categories'
    | '/api/export'
    | '/api/import'
    | '/api/investments'
    | '/api/recurring'
    | '/api/transactions'
    | '/transactions/new'
    | '/api/categories/$id'
    | '/api/investments/$id'
    | '/api/recurring/$id'
    | '/api/stats/category-breakdown'
    | '/api/stats/monthly-summary'
    | '/api/transactions/$id'
    | '/transactions/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/categories'
    | '/import'
    | '/investments'
    | '/recurring'
    | '/stats'
    | '/transactions'
    | '/api/categories'
    | '/api/export'
    | '/api/import'
    | '/api/investments'
    | '/api/recurring'
    | '/api/transactions'
    | '/transactions_/new'
    | '/api/categories/$id'
    | '/api/investments/$id'
    | '/api/recurring/$id'
    | '/api/stats/category-breakdown'
    | '/api/stats/monthly-summary'
    | '/api/transactions/$id'
    | '/transactions_/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoriesRoute: typeof CategoriesRoute
  ImportRoute: typeof ImportRoute
  InvestmentsRoute: typeof InvestmentsRoute
  RecurringRoute: typeof RecurringRoute
  StatsRoute: typeof StatsRoute
  TransactionsRoute: typeof TransactionsRoute
  ApiCategoriesRoute: typeof ApiCategoriesRouteWithChildren
  ApiExportRoute: typeof ApiExportRoute
  ApiImportRoute: typeof ApiImportRoute
  ApiInvestmentsRoute: typeof ApiInvestmentsRouteWithChildren
  ApiRecurringRoute: typeof ApiRecurringRouteWithChildren
  ApiTransactionsRoute: typeof ApiTransactionsRouteWithChildren
  TransactionsNewRoute: typeof TransactionsNewRoute
  ApiStatsCategoryBreakdownRoute: typeof ApiStatsCategoryBreakdownRoute
  ApiStatsMonthlySummaryRoute: typeof ApiStatsMonthlySummaryRoute
  TransactionsIdEditRoute: typeof TransactionsIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recurring': {
      id: '/recurring'
      path: '/recurring'
      fullPath: '/recurring'
      preLoaderRoute: typeof RecurringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investments': {
      id: '/investments'
      path: '/investments'
      fullPath: '/investments'
      preLoaderRoute: typeof InvestmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions_/new': {
      id: '/transactions_/new'
      path: '/transactions/new'
      fullPath: '/transactions/new'
      preLoaderRoute: typeof TransactionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transactions': {
      id: '/api/transactions'
      path: '/api/transactions'
      fullPath: '/api/transactions'
      preLoaderRoute: typeof ApiTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/recurring': {
      id: '/api/recurring'
      path: '/api/recurring'
      fullPath: '/api/recurring'
      preLoaderRoute: typeof ApiRecurringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/investments': {
      id: '/api/investments'
      path: '/api/investments'
      fullPath: '/api/investments'
      preLoaderRoute: typeof ApiInvestmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/import': {
      id: '/api/import'
      path: '/api/import'
      fullPath: '/api/import'
      preLoaderRoute: typeof ApiImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/export': {
      id: '/api/export'
      path: '/api/export'
      fullPath: '/api/export'
      preLoaderRoute: typeof ApiExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/categories': {
      id: '/api/categories'
      path: '/api/categories'
      fullPath: '/api/categories'
      preLoaderRoute: typeof ApiCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions_/$id/edit': {
      id: '/transactions_/$id/edit'
      path: '/transactions/$id/edit'
      fullPath: '/transactions/$id/edit'
      preLoaderRoute: typeof TransactionsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transactions/$id': {
      id: '/api/transactions/$id'
      path: '/$id'
      fullPath: '/api/transactions/$id'
      preLoaderRoute: typeof ApiTransactionsIdRouteImport
      parentRoute: typeof ApiTransactionsRoute
    }
    '/api/stats/monthly-summary': {
      id: '/api/stats/monthly-summary'
      path: '/api/stats/monthly-summary'
      fullPath: '/api/stats/monthly-summary'
      preLoaderRoute: typeof ApiStatsMonthlySummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stats/category-breakdown': {
      id: '/api/stats/category-breakdown'
      path: '/api/stats/category-breakdown'
      fullPath: '/api/stats/category-breakdown'
      preLoaderRoute: typeof ApiStatsCategoryBreakdownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/recurring/$id': {
      id: '/api/recurring/$id'
      path: '/$id'
      fullPath: '/api/recurring/$id'
      preLoaderRoute: typeof ApiRecurringIdRouteImport
      parentRoute: typeof ApiRecurringRoute
    }
    '/api/investments/$id': {
      id: '/api/investments/$id'
      path: '/$id'
      fullPath: '/api/investments/$id'
      preLoaderRoute: typeof ApiInvestmentsIdRouteImport
      parentRoute: typeof ApiInvestmentsRoute
    }
    '/api/categories/$id': {
      id: '/api/categories/$id'
      path: '/$id'
      fullPath: '/api/categories/$id'
      preLoaderRoute: typeof ApiCategoriesIdRouteImport
      parentRoute: typeof ApiCategoriesRoute
    }
  }
}

interface ApiCategoriesRouteChildren {
  ApiCategoriesIdRoute: typeof ApiCategoriesIdRoute
}

const ApiCategoriesRouteChildren: ApiCategoriesRouteChildren = {
  ApiCategoriesIdRoute: ApiCategoriesIdRoute,
}

const ApiCategoriesRouteWithChildren = ApiCategoriesRoute._addFileChildren(
  ApiCategoriesRouteChildren,
)

interface ApiInvestmentsRouteChildren {
  ApiInvestmentsIdRoute: typeof ApiInvestmentsIdRoute
}

const ApiInvestmentsRouteChildren: ApiInvestmentsRouteChildren = {
  ApiInvestmentsIdRoute: ApiInvestmentsIdRoute,
}

const ApiInvestmentsRouteWithChildren = ApiInvestmentsRoute._addFileChildren(
  ApiInvestmentsRouteChildren,
)

interface ApiRecurringRouteChildren {
  ApiRecurringIdRoute: typeof ApiRecurringIdRoute
}

const ApiRecurringRouteChildren: ApiRecurringRouteChildren = {
  ApiRecurringIdRoute: ApiRecurringIdRoute,
}

const ApiRecurringRouteWithChildren = ApiRecurringRoute._addFileChildren(
  ApiRecurringRouteChildren,
)

interface ApiTransactionsRouteChildren {
  ApiTransactionsIdRoute: typeof ApiTransactionsIdRoute
}

const ApiTransactionsRouteChildren: ApiTransactionsRouteChildren = {
  ApiTransactionsIdRoute: ApiTransactionsIdRoute,
}

const ApiTransactionsRouteWithChildren = ApiTransactionsRoute._addFileChildren(
  ApiTransactionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoriesRoute: CategoriesRoute,
  ImportRoute: ImportRoute,
  InvestmentsRoute: InvestmentsRoute,
  RecurringRoute: RecurringRoute,
  StatsRoute: StatsRoute,
  TransactionsRoute: TransactionsRoute,
  ApiCategoriesRoute: ApiCategoriesRouteWithChildren,
  ApiExportRoute: ApiExportRoute,
  ApiImportRoute: ApiImportRoute,
  ApiInvestmentsRoute: ApiInvestmentsRouteWithChildren,
  ApiRecurringRoute: ApiRecurringRouteWithChildren,
  ApiTransactionsRoute: ApiTransactionsRouteWithChildren,
  TransactionsNewRoute: TransactionsNewRoute,
  ApiStatsCategoryBreakdownRoute: ApiStatsCategoryBreakdownRoute,
  ApiStatsMonthlySummaryRoute: ApiStatsMonthlySummaryRoute,
  TransactionsIdEditRoute: TransactionsIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
